services:
  db:
    image: postgres:15-alpine
    container_name: msale3_db
    environment:
      POSTGRES_USER: msale3user
      POSTGRES_PASSWORD: msale3pass
      POSTGRES_DB: msale3db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: msale3_app
    environment:
      DB_URL: postgresql+psycopg2://msale3user:msale3pass@db:5432/msale3db
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
